import type { Transaction, FailureSummary, TrendPoint, FailureReason } from './types';

const avatarColors = [
  'from-emerald-400 to-teal-500',
  'from-sky-400 to-blue-500',
  'from-amber-400 to-orange-500',
  'from-rose-400 to-pink-500',
  'from-violet-400 to-indigo-500',
  'from-cyan-400 to-teal-500',
  'from-lime-400 to-green-500',
  'from-fuchsia-400 to-purple-500',
];

export const transactions: Transaction[] = [
  {
    id: 'TXN-1042',
    customerName: 'Sarah Chen',
    customerEmail: 'sarah.chen@gmail.com',
    customerPhone: '+1 (415) 555-0182',
    avatarColor: avatarColors[0],
    amount: 249.99,
    currency: 'USD',
    merchant: 'TechNova Electronics',
    productDescription: 'Wireless Noise-Cancelling Headphones',
    failureReason: 'Insufficient Funds',
    status: 'Recovered',
    recoveryScore: 82,
    attemptedAt: '2026-09-04T14:32:00Z',
    recoverySentAt: '2026-09-04T15:01:00Z',
    recoveredAt: '2026-09-04T16:45:00Z',
    aiReasoning:
      "The transaction was declined with code 51 (insufficient funds), but the customer's account shows a scheduled direct deposit in 2 days. Their browsing session lasted 18 minutes with 3 product page visits, indicating strong purchase intent. The item is a mid-ticket electronics purchase typically associated with planned spending. Recovery likelihood is high if we time the nudge after the expected deposit clears.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi Sarah! We noticed your headphones order didn't go through — no worries, it happens! We've saved your cart with free shipping still applied. Your discount code FREESHIP is locked in for 24 hours. Ready to try again? Tap here: payreclaim.link/s1042",
      tone: 'Friendly & helpful',
    },
  },
  {
    id: 'TXN-1041',
    customerName: 'Marcus Okafor',
    customerEmail: 'marcus.o@outlook.com',
    customerPhone: '+1 (212) 555-0293',
    avatarColor: avatarColors[1],
    amount: 89.00,
    currency: 'USD',
    merchant: 'Urban Threads Co.',
    productDescription: 'Premium Cotton Hoodie (2 items)',
    failureReason: 'OTP Timeout',
    status: 'Recovered',
    recoveryScore: 91,
    attemptedAt: '2026-09-04T11:15:00Z',
    recoverySentAt: '2026-09-04T11:42:00Z',
    recoveredAt: '2026-09-04T12:08:00Z',
    aiReasoning:
      "OTP timeout on a $89 fashion purchase. The customer completed all checkout steps and reached the bank verification page, meaning the purchase intent is very strong. OTP timeouts are almost always transient — the user was likely distracted or had poor cell signal. This is one of the most recoverable failure types. A prompt, frictionless retry will almost certainly convert.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hey Marcus! Your Urban Threads order is still waiting — looks like the verification step timed out. Super easy fix: just tap the link below to pick up right where you left off. Your hoodie sizes are reserved for the next 2 hours! payreclaim.link/m1041",
      tone: 'Casual & energetic',
    },
  },
  {
    id: 'TXN-1040',
    customerName: 'Elena Rodriguez',
    customerEmail: 'elena.r@protonmail.com',
    customerPhone: '+1 (305) 555-0471',
    avatarColor: avatarColors[2],
    amount: 1299.00,
    currency: 'USD',
    merchant: 'Apex Fitness Gear',
    productDescription: 'Smart Treadmill Pro X1',
    failureReason: 'Card Declined',
    status: 'Pending',
    recoveryScore: 34,
    attemptedAt: '2026-09-04T09:48:00Z',
    recoverySentAt: '2026-09-04T10:15:00Z',
    recoveredAt: null,
    aiReasoning:
      "Generic card decline (code 05 — do not honor) on a high-value $1,299 transaction. The bank's risk engine flagged the purchase amount as unusual for this cardholder's spending pattern. The customer has no prior purchase history with this merchant. Recovery is possible but unlikely without offering installment options or a lower-friction payment method like a wallet or BNPL.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Your Apex Fitness order is still here — flexible payment options inside',
      body: "Hi Elena,\n\nWe noticed your Smart Treadmill Pro X1 order didn't complete — sometimes banks put large purchases on hold for security. Good news: we now offer 4 interest-free installment payments of just $324.75, so you can get moving without the upfront cost.\n\nYour cart is saved and ready. Want to try a different card or split the payment? It takes less than a minute.\n\n[Resume Checkout]  [Pay in Installments]\n\n— The Apex Fitness Team",
      tone: 'Professional & solution-oriented',
    },
  },
  {
    id: 'TXN-1039',
    customerName: 'James Park',
    customerEmail: 'jamespark@gmail.com',
    customerPhone: '+1 (206) 555-0119',
    avatarColor: avatarColors[3],
    amount: 49.99,
    currency: 'USD',
    merchant: 'BrewBox Coffee',
    productDescription: 'Monthly Coffee Subscription',
    failureReason: 'Network Drop',
    status: 'Recovery Sent',
    recoveryScore: 88,
    attemptedAt: '2026-09-03T18:22:00Z',
    recoverySentAt: '2026-09-03T18:40:00Z',
    recoveredAt: null,
    aiReasoning:
      "Network drop during checkout — the payment request was interrupted mid-transmission, not declined by the bank. This is purely a connectivity issue with zero relationship to the customer's financial standing or intent. Recurring subscription purchases show consistent intent. The customer is on a recurring billing cycle, so they're already committed. Recovery probability is very high.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi James! Your BrewBox subscription signup hit a small network hiccup. We've kept everything ready — just tap below to confirm and your first batch of fresh-roasted coffee ships tomorrow morning. ☕ payreclaim.link/j1039",
      tone: 'Warm & inviting',
    },
  },
  {
    id: 'TXN-1038',
    customerName: 'Priya Nair',
    customerEmail: 'priya.nair@yahoo.com',
    customerPhone: '+1 (408) 555-0667',
    avatarColor: avatarColors[4],
    amount: 179.50,
    currency: 'USD',
    merchant: 'Glow Beauty Lab',
    productDescription: 'Skincare Bundle — Vitamin C + Retinol',
    failureReason: 'Insufficient Funds',
    status: 'Lost',
    recoveryScore: 22,
    attemptedAt: '2026-09-03T13:05:00Z',
    recoverySentAt: '2026-09-03T13:30:00Z',
    recoveredAt: null,
    aiReasoning:
      "Insufficient funds on a discretionary beauty purchase. The customer's account balance is well below the purchase amount, and there's no scheduled deposit in the next 7 days. The product is a non-essential luxury item, meaning the customer is unlikely to rearrange finances to complete it. Two prior recovery attempts went unopened. Recovery probability is low.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Still thinking about your skincare routine? Here\u2019s a little help',
      body: "Hi Priya,\n\nWe noticed your skincare bundle didn't go through this time. If budget is the hold-up, we've got you — use code GLOW15 for 15% off your bundle, bringing it to just $152.58. Your skin deserves it, and this code is good for the next 48 hours.\n\n[Complete Your Order]\n\nWarmly,\nThe Glow Beauty Lab Team",
      tone: 'Gentle & empathetic',
    },
  },
  {
    id: 'TXN-1037',
    customerName: 'David Thompson',
    customerEmail: 'd.thompson@corporate.net',
    customerPhone: '+1 (617) 555-0834',
    avatarColor: avatarColors[5],
    amount: 599.00,
    currency: 'USD',
    merchant: 'CloudSoft SaaS',
    productDescription: 'Annual Business Plan Subscription',
    failureReason: 'Fraud Suspected',
    status: 'Recovery Sent',
    recoveryScore: 58,
    attemptedAt: '2026-09-03T10:11:00Z',
    recoverySentAt: '2026-09-03T10:45:00Z',
    recoveredAt: null,
    aiReasoning:
      "The bank flagged this as potentially fraudulent (code 59 — suspected fraud). However, the customer used a corporate email and the IP geolocation matches the billing address. This is likely a false positive from the bank's risk engine, triggered by the annual billing cycle amount. Providing the customer with a direct link to confirm with their bank, plus a simplified retry, gives a moderate recovery chance.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Action needed: Verify your CloudSoft Business plan purchase',
      body: "Hi David,\n\nYour CloudSoft Business plan purchase was flagged by your bank's security system — this sometimes happens with annual billing amounts. A quick call to your card issuer (number on the back of your card) to confirm the charge will unblock it immediately.\n\nOnce confirmed, just click below to retry — everything is pre-filled and ready to go.\n\n[Retry Checkout]\n\nBest,\nThe CloudSoft Team",
      tone: 'Clear & instructional',
    },
  },
  {
    id: 'TXN-1036',
    customerName: 'Aisha Mohammed',
    customerEmail: 'aisha.m@gmail.com',
    customerPhone: '+1 (703) 555-0928',
    avatarColor: avatarColors[6],
    amount: 65.00,
    currency: 'USD',
    merchant: 'PetPal Supplies',
    productDescription: 'Premium Dog Food + Treats Bundle',
    failureReason: 'OTP Timeout',
    status: 'Recovered',
    recoveryScore: 93,
    attemptedAt: '2026-09-02T19:33:00Z',
    recoverySentAt: '2026-09-02T19:50:00Z',
    recoveredAt: '2026-09-02T20:15:00Z',
    aiReasoning:
      "OTP timeout on a recurring pet supply purchase. The customer has ordered from this merchant 4 times previously, and the cart contains the same products as prior orders. The purchase intent is essentially confirmed by behavioral history. OTP timeouts are the highest-recovery failure type. An immediate retry nudge will convert with near certainty.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi Aisha! Your PetPal order got interrupted at the verification step — no problem at all! Your dog's favorites are all set and ready to ship. Just tap to confirm and delivery will be on its way by tomorrow. 🐾 payreclaim.link/a1036",
      tone: 'Cheerful & personal',
    },
  },
  {
    id: 'TXN-1035',
    customerName: 'Ryan Mitchell',
    customerEmail: 'ryan.mitchell@gmail.com',
    customerPhone: '+1 (512) 555-0351',
    avatarColor: avatarColors[7],
    amount: 329.00,
    currency: 'USD',
    merchant: 'GameVault',
    productDescription: 'Next-Gen Console Bundle',
    failureReason: 'Card Declined',
    status: 'Pending',
    recoveryScore: 47,
    attemptedAt: '2026-09-02T15:44:00Z',
    recoverySentAt: '2026-09-02T16:10:00Z',
    recoveredAt: null,
    aiReasoning:
      "Card declined with a generic code 05. The customer is a first-time buyer with no purchase history. However, the browsing session was long (32 minutes) with repeated visits to the product page, suggesting strong desire but possible payment constraint. Offering an alternative payment method or a small discount could tip the decision. Moderate recovery chance.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Your console bundle is waiting, Ryan — plus a surprise',
      body: "Hey Ryan,\n\nWe saw your checkout didn't finish — sometimes banks get cautious with bigger gaming purchases. Here's something to help: use code GAMEON10 for 10% off your bundle, making it just $296.10. You can also pay with Apple Pay, Google Pay, or split it into 4 payments.\n\nYour console is reserved for 6 hours. Ready to get your game on?\n\n[Resume & Save 10%]  [Pay in 4]\n\n— The GameVault Crew",
      tone: 'Enthusiastic & incentivizing',
    },
  },
  {
    id: 'TXN-1034',
    customerName: 'Sophie Laurent',
    customerEmail: 'sophie.laurent@gmail.com',
    customerPhone: '+1 (917) 555-0214',
    avatarColor: avatarColors[0],
    amount: 145.00,
    currency: 'USD',
    merchant: 'Maison Home Decor',
    productDescription: 'Linen Throw Pillows Set (3)',
    failureReason: 'Expired Card',
    status: 'Recovery Sent',
    recoveryScore: 76,
    attemptedAt: '2026-09-02T12:18:00Z',
    recoverySentAt: '2026-09-02T12:45:00Z',
    recoveredAt: null,
    aiReasoning:
      "The card on file expired last month. The customer is a repeat buyer (2 prior purchases) with a saved card, indicating trust and convenience preference. An expired card is a high-recovery failure type — the customer simply needs to update their payment details. A clear, low-friction prompt to add a new card will likely convert, especially for a repeat customer.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Quick update needed for your Maison order, Sophie',
      body: "Bonjour Sophie!\n\nIt looks like the card saved to your account has expired — no worries, it happens to the best of us. Your linen pillow set is safely in your cart and waiting. Just update your card details with one tap and you're all set.\n\n[Update & Complete Order]\n\nWe can't wait to see how these look in your space!\n\nWarmly,\nThe Maison Home Team",
      tone: 'Elegant & warm',
    },
  },
  {
    id: 'TXN-1033',
    customerName: 'Carlos Mendez',
    customerEmail: 'carlos.mendez@hotmail.com',
    customerPhone: '+1 (323) 555-0582',
    avatarColor: avatarColors[1],
    amount: 75.00,
    currency: 'USD',
    merchant: 'MealPrep Express',
    productDescription: 'Weekly Meal Plan (5 meals)',
    failureReason: 'Network Drop',
    status: 'Recovered',
    recoveryScore: 90,
    attemptedAt: '2026-09-01T17:55:00Z',
    recoverySentAt: '2026-09-01T18:12:00Z',
    recoveredAt: '2026-09-01T18:35:00Z',
    aiReasoning:
      "Network drop during a recurring weekly meal plan payment. The customer has been a subscriber for 3 months with consistent weekly orders. Network drops are purely transient and unrelated to financial capacity. The recurring subscription model means the customer expects this charge. Very high recovery probability with a simple retry prompt.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi Carlos! Your MealPrep order hit a quick network bump — all good! Your 5 meals are prepped and ready. Just tap below to confirm and we'll have them at your door by 6am tomorrow. payreclaim.link/c1033",
      tone: 'Friendly & reassuring',
    },
  },
  {
    id: 'TXN-1032',
    customerName: 'Hannah Kim',
    customerEmail: 'hannah.kim@gmail.com',
    customerPhone: '+1 (818) 555-0745',
    avatarColor: avatarColors[2],
    amount: 199.00,
    currency: 'USD',
    merchant: 'Lumina Skincare',
    productDescription: 'LED Light Therapy Device',
    failureReason: 'Insufficient Funds',
    status: 'Pending',
    recoveryScore: 41,
    attemptedAt: '2026-09-01T14:20:00Z',
    recoverySentAt: '2026-09-01T14:50:00Z',
    recoveredAt: null,
    aiReasoning:
      "Insufficient funds on a $199 discretionary beauty device. The customer is a new visitor with no purchase history. The account has no upcoming deposits in the next 5 days, and the product is a non-essential item. However, the customer spent 12 minutes on the product page reading reviews, suggesting genuine interest. A time-limited discount could create urgency, but recovery is uncertain.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Hannah, your LED therapy device is still in your cart',
      body: "Hi Hannah,\n\nWe noticed you didn't finish checking out your Lumina LED device — we know it's an investment. Here's a little nudge: for the next 48 hours, take $30 off with code GLOW30, bringing it to $169. Plus free shipping and a 60-day money-back guarantee.\n\nYour cart is saved and ready whenever you are.\n\n[Complete Your Order — Save $30]\n\n— The Lumina Skincare Team",
      tone: 'Encouraging & value-driven',
    },
  },
  {
    id: 'TXN-1031',
    customerName: 'Thomas Wright',
    customerEmail: 't.wright@business.com',
    customerPhone: '+1 (704) 555-0339',
    avatarColor: avatarColors[3],
    amount: 450.00,
    currency: 'USD',
    merchant: 'OfficePro Supplies',
    productDescription: 'Ergonomic Office Chair',
    failureReason: 'Fraud Suspected',
    status: 'Lost',
    recoveryScore: 15,
    attemptedAt: '2026-09-01T09:30:00Z',
    recoverySentAt: '2026-09-01T10:00:00Z',
    recoveredAt: null,
    aiReasoning:
      "Bank fraud flag with mismatched billing and shipping addresses, plus the card was used from a VPN IP. The transaction has multiple legitimate fraud signals. Recovery attempts were sent but went unopened for 48 hours. The customer may have been using a forwarding service, but the risk profile is too high to pursue aggressively. Low recovery probability — marking as lost.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Confirm your OfficePro chair purchase',
      body: "Hi Thomas,\n\nYour ergonomic chair order was paused by your bank's security check. To complete this purchase, please call your card provider to authorize the charge, then click below to retry.\n\n[Retry Checkout]\n\nIf this wasn't you, please disregard this email.\n\n— OfficePro Supplies",
      tone: 'Formal & cautious',
    },
  },
  {
    id: 'TXN-1030',
    customerName: 'Maya Patel',
    customerEmail: 'maya.patel@gmail.com',
    customerPhone: '+1 (404) 555-0167',
    avatarColor: avatarColors[4],
    amount: 120.00,
    currency: 'USD',
    merchant: 'BookNest',
    productDescription: 'Signed Edition Book Bundle (5 books)',
    failureReason: 'OTP Timeout',
    status: 'Recovered',
    recoveryScore: 95,
    attemptedAt: '2026-08-31T20:10:00Z',
    recoverySentAt: '2026-08-31T20:25:00Z',
    recoveredAt: '2026-08-31T20:48:00Z',
    aiReasoning:
      "OTP timeout on a limited-edition book bundle. The customer is a loyalty program member with 6 prior purchases and specifically opted into the waitlist for this signed edition. Purchase intent is extremely high — the customer actively waited for this product. OTP timeouts are the most recoverable failure type. An immediate, warm retry nudge will convert with very high probability.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi Maya! Great news — your signed book bundle is secured! The verification step just needs a quick retry. These are limited edition, so tap below to confirm before they're gone. Your waitlist spot is locked in! 📚 payreclaim.link/m1030",
      tone: 'Excited & urgent',
    },
  },
  {
    id: 'TXN-1029',
    customerName: 'Liam Murphy',
    customerEmail: 'liam.murphy@gmail.com',
    customerPhone: '+1 (646) 555-0892',
    avatarColor: avatarColors[5],
    amount: 310.00,
    currency: 'USD',
    merchant: 'TrailHead Outdoors',
    productDescription: 'Hiking Backpack + Tent Bundle',
    failureReason: 'Card Declined',
    status: 'Recovery Sent',
    recoveryScore: 63,
    attemptedAt: '2026-08-31T16:47:00Z',
    recoverySentAt: '2026-08-31T17:15:00Z',
    recoveredAt: null,
    aiReasoning:
      "Card declined (code 05) on an outdoor gear purchase. The customer has 1 prior purchase with this merchant and spent 22 minutes comparing products. The decline is generic, not fraud-related, suggesting the bank may have a daily spending limit trigger. Offering a split-payment option or a different card could resolve it. Moderate-to-good recovery chance.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Your adventure gear is ready when you are, Liam',
      body: "Hey Liam,\n\nYour hiking bundle is all packed and ready — it looks like your card hit a snag. No worries! You can switch to a different card, pay with Apple Pay, or split the cost into 4 payments of $77.50.\n\nYour gear is reserved for 12 hours. Adventure's calling!\n\n[Resume Checkout]  [Pay in 4]\n\n— The TrailHead Team",
      tone: 'Adventurous & upbeat',
    },
  },
  {
    id: 'TXN-1028',
    customerName: 'Zoe Anderson',
    customerEmail: 'zoe.anderson@gmail.com',
    customerPhone: '+1 (503) 555-0423',
    avatarColor: avatarColors[6],
    amount: 55.00,
    currency: 'USD',
    merchant: 'PlantParenthood',
    productDescription: 'Indoor Plant Starter Kit',
    failureReason: 'Expired Card',
    status: 'Recovered',
    recoveryScore: 84,
    attemptedAt: '2026-08-30T11:28:00Z',
    recoverySentAt: '2026-08-30T11:55:00Z',
    recoveredAt: '2026-08-30T12:30:00Z',
    aiReasoning:
      "Expired card on a low-ticket purchase. The customer has made 3 prior purchases and has a saved payment method, so the expired card is simply an oversight. Low-ticket items have lower commitment barriers, and the customer's history shows consistent interest. Expired card failures are highly recoverable — a simple update prompt will likely convert.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi Zoe! Your plant starter kit order just needs a quick card update — your saved card has expired. Easy fix: tap below, update your details, and your green friends will be on their way! 🌱 payreclaim.link/z1028",
      tone: 'Playful & light',
    },
  },
  {
    id: 'TXN-1027',
    customerName: 'Noah Goldberg',
    customerEmail: 'noah.g@gmail.com',
    customerPhone: '+1 (310) 555-0175',
    avatarColor: avatarColors[7],
    amount: 185.00,
    currency: 'USD',
    merchant: 'SoundWave Audio',
    productDescription: 'Portable Bluetooth Speaker (Premium)',
    failureReason: 'Network Drop',
    status: 'Recovery Sent',
    recoveryScore: 85,
    attemptedAt: '2026-08-30T08:40:00Z',
    recoverySentAt: '2026-08-30T09:05:00Z',
    recoveredAt: null,
    aiReasoning:
      "Network drop on a mid-ticket electronics purchase. The customer added the item to cart immediately on first visit and reached checkout in under 5 minutes, showing decisive buying behavior. Network drops are transient and unrelated to payment capacity. The fast decision-to-checkout time is a strong positive signal. High recovery probability with a prompt retry.",
    recoveryMessage: {
      channel: 'SMS',
      body: "Hi Noah! Quick heads up — your SoundWave speaker order got cut off by a network blip. Your cart's all set, just tap to finish and we'll ship it out today with free 2-day delivery. payreclaim.link/n1027",
      tone: 'Direct & efficient',
    },
  },
  {
    id: 'TXN-1026',
    customerName: 'Grace Liu',
    customerEmail: 'grace.liu@gmail.com',
    customerPhone: '+1 (510) 555-0638',
    avatarColor: avatarColors[0],
    amount: 78.00,
    currency: 'USD',
    merchant: 'ArtisanBox',
    productDescription: 'Monthly Craft Subscription Box',
    failureReason: 'Insufficient Funds',
    status: 'Lost',
    recoveryScore: 18,
    attemptedAt: '2026-08-29T15:12:00Z',
    recoverySentAt: '2026-08-29T15:40:00Z',
    recoveredAt: null,
    aiReasoning:
      "Insufficient funds on a new subscription signup. The customer has no prior relationship with the merchant and no recurring billing history. The account has no scheduled deposits, and the recovery email was opened but no action taken after 72 hours. The combination of no relationship, no funds, and no response makes this a low-probability recovery. Recommended to mark as lost.",
    recoveryMessage: {
      channel: 'Email',
      subject: 'Your ArtisanBox is ready whenever you are',
      body: "Hi Grace,\n\nYour craft subscription box is still waiting! If now isn't the right time, no worries — we'll be here when you're ready. Use code WELCOME20 for 20% off your first box whenever you'd like to join.\n\n[Start Your Craft Journey]\n\n— The ArtisanBox Team",
      tone: 'Low-pressure & open-ended',
    },
  },
  {
    id: 'TXN-1025',
    customerName: 'Daniel Foster',
    customerEmail: 'daniel.foster@gmail.com',
    customerPhone: '+1 (480) 555-0287',
    avatarColor: avatarColors[1],
    amount: 395.00,
    currency: 'USD',
    merchant: 'ProCamera Online',
    productDescription: 'Mirrorless Camera Lens 50mm',
    failureReason: 'Card Declined',
    status: 'Recovered',
    recoveryScore: 71,
    attemptedAt: '2026-08-29T10:25:00Z',
    recoverySentAt: '2026-08-29T10:50:00Z',
    recoveredAt: '2026-08-29T12:15:00Z',
    aiReasoning:
      "Card declined on a camera lens purchase. The customer is a photography enthusiast who has browsed this product 5 times over 2 weeks, showing persistent strong intent. The decline was generic (code 05), not fraud. The repeated visits suggest the customer is committed to this specific purchase and likely has the funds but hit a bank limit. Offering an alternative payment method led to successful recovery.",
    recoveryMessage: {
      channel: 'Email',
      subject: "Daniel, the lens you've been eyeing is still available",
      body: "Hi Daniel,\n\nWe've noticed you've been checking out the 50mm lens — great taste! Your checkout didn't go through, but we've kept your cart ready. You can complete your order with any card, Apple Pay, or 4 interest-free payments of $98.75.\n\n[Finish Your Order]\n\nCapture something amazing,\nThe ProCamera Team",
      tone: 'Knowledgeable & encouraging',
    },
  },
];

export const failureReasons: FailureReason[] = [
  'Insufficient Funds',
  'OTP Timeout',
  'Network Drop',
  'Card Declined',
  'Expired Card',
  'Fraud Suspected',
];

export function getFailureSummaries(txns: Transaction[]): FailureSummary[] {
  return failureReasons.map((reason) => {
    const matching = txns.filter((t) => t.failureReason === reason);
    return {
      reason,
      count: matching.length,
      recovered: matching.filter((t) => t.status === 'Recovered').length,
      lost: matching.filter((t) => t.status === 'Lost').length,
      pending: matching.filter((t) => t.status === 'Pending' || t.status === 'Recovery Sent').length,
      amount: matching.reduce((sum, t) => sum + t.amount, 0),
    };
  });
}

export function getTrendData(txns: Transaction[]): TrendPoint[] {
  const dates = Array.from(new Set(txns.map((t) => t.attemptedAt.slice(0, 10)))).sort();
  return dates.map((date) => ({
    date,
    recovered: txns.filter((t) => t.status === 'Recovered' && t.recoveredAt?.slice(0, 10) === date).length,
    lost: txns.filter((t) => t.status === 'Lost' && t.attemptedAt.slice(0, 10) === date).length,
  }));
}

export function getStats(txns: Transaction[]) {
  const total = txns.length;
  const recovered = txns.filter((t) => t.status === 'Recovered');
  const lost = txns.filter((t) => t.status === 'Lost');
  const pending = txns.filter((t) => t.status === 'Pending' || t.status === 'Recovery Sent');
  const recoveredAmount = recovered.reduce((sum, t) => sum + t.amount, 0);
  const lostAmount = lost.reduce((sum, t) => sum + t.amount, 0);
  const pendingAmount = pending.reduce((sum, t) => sum + t.amount, 0);
  const recoveryRate = total > 0 ? Math.round((recovered.length / total) * 100) : 0;
  const avgScore = total > 0 ? Math.round(txns.reduce((sum, t) => sum + t.recoveryScore, 0) / total) : 0;

  return {
    total,
    recoveredCount: recovered.length,
    lostCount: lost.length,
    pendingCount: pending.length,
    recoveredAmount,
    lostAmount,
    pendingAmount,
    recoveryRate,
    avgScore,
  };
}
